// typedef enum {
//   TM_INDEX,
//   TM_NEWINDEX,
//   TM_GC,
//   TM_MODE,
//   TM_LEN,
//   TM_EQ,  /* last tag method with fast access */
//   TM_ADD,
//   TM_SUB,
//   TM_MUL,
//   TM_MOD,
//   TM_POW,
//   TM_DIV,
//   TM_IDIV,
//   TM_BAND,
//   TM_BOR,
//   TM_BXOR,
//   TM_SHL,
//   TM_SHR,
//   TM_UNM,
//   TM_BNOT,
//   TM_LT,
//   TM_LE,
//   TM_CONCAT,
//   TM_CALL,
//   TM_CLOSE,
//   TM_N		/* number of elements in the enum */
// } TMS;
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
#[allow(dead_code)]
pub enum TmKind {
    Index = 0,
    NewIndex = 1,
    Gc = 2,
    Mode = 3,
    Len = 4,
    Eq = 5,
    Add = 6,
    Sub = 7,
    Mul = 8,
    Mod = 9,
    Pow = 10,
    Div = 11,
    IDiv = 12,
    Band = 13,
    Bor = 14,
    Bxor = 15,
    Shl = 16,
    Shr = 17,
    Unm = 18,
    Bnot = 19,
    Lt = 20,
    Le = 21,
    Concat = 22,
    Call = 23,
    Close = 24,
    N = 25, // number of elements in the enum
}
